export interface Catalog {
    id: number,
    title: string,
    subTitle: string,
    model: string,
    capacity: string,
    imageUrl: string,
    price: number,
    stockKeepingUnit: string,
    discount: string,
    discountedPrice: string,
    hasActivePlasma: boolean,
    isDeleted: boolean,
    category: string,
    isPromoActive: boolean,
    promoStickerImageUrl: string,
    isMiniBannerActive: boolean,
    miniBannerStickerImageUrl: string,
    isWarrantyActive: boolean,
    warrantyStickerImageUrl: string,
    featureImages: any,
    productImages: any
    warehouseCatalogs: any,
}
